services:
  mongodb:
    image: mongo:8.0-noble
    container_name: mongodb
    restart: unless-stopped
    environment:
      MONGO_INITDB_DATABASE: manwha-tracker
    ports:
      - '27017:27017'
    volumes:
      - mongo-data:/data/db

volumes:
  mongo-data:
    driver: local
