services:
  mongo:
    image: mongo:8.0-noble
    container_name: mongo
    restart: unless-stopped
    environment:
      MONGO_INITDB_DATABASE: manhwa-tracker
    ports:
      - '27017:27017'
    volumes:
      - mongo-data:/data/db

  mongo-express:
    image: mongo-express:1.0-20-alpine3.19
    container_name: mongo-express
    restart: unless-stopped
    environment:
      ME_CONFIG_MONGODB_SERVER: mongo
      ME_CONFIG_MONGODB_PORT: 27017
    ports:
      - '8081:8081'

volumes:
  mongo-data:
    driver: local
